# Generated by Django 5.0 on 2024-07-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_create_users_and_roles_tables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pvdmusers1',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'Admin'), ('hr_manager', 'HR Manager'), ('hr_staff', 'HR'), ('historic_staff', 'Historic Staff'), ('general_staff', 'General Staff'), ('it_manager', 'IT Manager')], max_length=50, unique=True),
        ),
    ]
