# Generated by Django 5.0 on 2024-07-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0002_pvcapindex1_pvcapindexvalue1_pvcapjob1'),
    ]

    operations = [
       
        migrations.CreateModel(
            name='PvcapBatch1',
            fields=[
                ('batchid', models.BigAutoField(db_column='BATCHID', primary_key=True, serialize=False)),
                ('internalname', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='INTERNALNAME', max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='NAME', max_length=255, null=True)),
                ('description', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='DESCRIPTION', max_length=255, null=True)),
                ('userdate', models.DateTimeField(blank=True, db_column='USERDATE', null=True)),
                ('path', models.TextField(db_collation='Latin1_General_CI_AS', db_column='PATH')),
                ('isdeleted', models.BooleanField(db_column='ISDELETED')),
                ('isnew', models.BooleanField(db_column='ISNEW')),
                ('retainstats', models.BooleanField(db_column='RETAINSTATS')),
                ('adminpriority', models.BigIntegerField(db_column='ADMINPRIORITY')),
                ('status', models.SmallIntegerField(db_column='STATUS')),
                ('jobid', models.BigIntegerField(db_column='JOBID')),
                ('jobstart', models.DateTimeField(db_column='JOBSTART')),
                ('stepid', models.IntegerField(db_column='STEPID')),
                ('stepstart', models.DateTimeField(db_column='STEPSTART')),
                ('checkedoutbydatetime', models.DateTimeField(blank=True, db_column='CHECKEDOUTBYDATETIME', null=True)),
                ('checkedoutbyuserid', models.IntegerField(blank=True, db_column='CHECKEDOUTBYUSERID', null=True)),
                ('checkedoutbyworkstation', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='CHECKEDOUTBYWORKSTATION', max_length=255, null=True)),
                ('scheduleddestruction', models.DateTimeField(blank=True, db_column='SCHEDULEDDESTRUCTION', null=True)),
                ('size', models.BigIntegerField(db_column='SIZE')),
                ('lastupdate', models.DateTimeField(db_column='LASTUPDATE')),
                ('documentcount', models.BigIntegerField(blank=True, db_column='DOCUMENTCOUNT', null=True)),
                ('pagecount', models.BigIntegerField(blank=True, db_column='PAGECOUNT', null=True)),
                ('imagecount', models.BigIntegerField(blank=True, db_column='IMAGECOUNT', null=True)),
                ('delayprocessing', models.DateTimeField(blank=True, db_column='DELAYPROCESSING', null=True)),
                ('iscomplete', models.BooleanField(db_column='ISCOMPLETE', default=False)),
                ('userid', models.IntegerField(db_column='USERID')),
            ],
            options={
                'db_table': 'PVCAP_BATCH_1',
                'managed': True,
            },
        ),
    ]