# Generated by Django 5.0 on 2024-10-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0003_new_column_to_batches_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PvcapBundle',
            fields=[
                ('bundleid', models.BigAutoField(db_column='BUNDLEID', primary_key=True, serialize=False)),
                ('batchid', models.IntegerField(db_column='BATCHID')),
                ('createdate', models.DateTimeField(db_column='CREATEDATE', null=True)),
                ('submit', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'PvcapBundle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PvcapIndex1',
            fields=[
                ('indexid', models.BigIntegerField(db_column='INDEXID', primary_key=True, serialize=False)),
                ('jobid', models.BigIntegerField(db_column='JOBID')),
                ('fieldname', models.CharField(db_collation='Latin1_General_CI_AS', db_column='FIELDNAME', max_length=255)),
                ('indexproperties', models.TextField(blank=True, db_collation='Latin1_General_CI_AS', db_column='INDEXPROPERTIES', null=True)),
            ],
            options={
                'db_table': 'PVCAP_INDEX_1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PvcapIndexvalue1',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('jobid', models.BigIntegerField(db_column='JOBID')),
                ('indexid', models.BigIntegerField(db_column='INDEXID')),
                ('value', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='VALUE', max_length=255, null=True)),
                ('batchid', models.BigIntegerField(db_column='BATCHID')),
                ('bundleid', models.BigIntegerField(db_column='BUNDLEID')),
                ('detailsetid', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='DETAILSETID', max_length=255, null=True)),
                ('confidence', models.FloatField(blank=True, db_column='CONFIDENCE', null=True)),
                ('rowindex', models.IntegerField(blank=True, db_column='ROWINDEX', null=True)),
            ],
            options={
                'db_table': 'PVCAP_INDEXVALUE_1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PvcapJob1',
            fields=[
                ('jobid', models.BigAutoField(db_column='JOBID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='Latin1_General_CI_AS', db_column='NAME', max_length=255)),
                ('description', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='DESCRIPTION', max_length=255, null=True)),
                ('comment', models.TextField(blank=True, db_collation='Latin1_General_CI_AS', db_column='COMMENT', null=True)),
                ('modifieddatetime', models.DateTimeField(blank=True, db_column='MODIFIEDDATETIME', null=True)),
                ('modifiedbyname', models.IntegerField(blank=True, db_column='MODIFIEDBYNAME', null=True)),
                ('modifiedbyglobaladmin', models.BooleanField(blank=True, db_column='MODIFIEDBYGLOBALADMIN', null=True)),
                ('checkedoutbydatetime', models.DateTimeField(blank=True, db_column='CHECKEDOUTBYDATETIME', null=True)),
                ('checkedoutbyname', models.IntegerField(blank=True, db_column='CHECKEDOUTBYNAME', null=True)),
                ('checkedoutbyglobaladmin', models.BooleanField(blank=True, db_column='CHECKEDOUTBYGLOBALADMIN', null=True)),
                ('properties', models.TextField(blank=True, db_collation='Latin1_General_CI_AS', db_column='PROPERTIES', null=True)),
            ],
            options={
                'db_table': 'PVCAP_JOB_1',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='pvcapbatch1',
            options={'managed': False},
        ),
    ]
