# Generated by Django 5.0 on 2024-10-09 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0004_pvcapbundle_pvcapindex1_pvcapindexvalue1_pvcapjob1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pvcapindexvalue1',
            options={'managed': True},
        ),
    ]
