from django.urls import path
from . import views



urlpatterns =[
    path('', views.landingBatches, name="landingBatches"),
    path('general_search/', views.general_search, name="generalResults"),
    path('filling-batch/', views.fillingBatch, name="fillingBatch"),
    path('civil-search/', views.civilSearch, name="civilSearch"),
    path('civil-results/', views.civilResults, name="civilResults"),
    path('criminal-cases-search/', views.criminalCasesSearch, name="criminalCasesSearch"),
    path('criminal-cases-results/', views.criminalCasesResults, name="criminalCasesResults"),
    path('criminal-juvenile-search/', views.criminalJuvenileSearch, name="criminalJuvenileSearch"),
    path('criminal-juvenile-results/', views.criminalJuvenileResults, name="criminalJuvenileResults"),
    path('criminal-search/', views.criminalSearch, name="criminalSearch"),
    path('criminal-results/', views.criminalResults, name="criminalResults"),
    path('historic-index-cards-search/', views.historicIndexCardsSearch, name="historicIndexCardsSearch"),
    path('historic-index-cards-results/', views.historicIndexCardsResults, name="historicIndexCardsResults"),
    path('historic-order-books-search/', views.historicOrderBooksSearch, name="historicOrderBooksSearch"),
    path('historic-order-books-results/', views.historicOrderBooksResults, name="historicOrderBooksResults"),
    path('hr-search/', views.hrSearch, name="hrSearch"),
    path('hr-results/', views.hrResults, name="hrResults"),
    path('bond-search/', views.bondBooksSearch, name="bondBooksSearch"),
    path('bond-results/', views.bondBooksResults, name="bondBooksResults"),
    path('concealed-weapons-search/', views.ConcealedWeaponsSearch, name="ConcealedWeaponsSearch"),
    path('concealed-weapons-results/', views.ConcealedWeaponsResults, name="ConcealedWeaponsResults"),
    path('charters-Search/', views.chartersSearch, name="chartersSearch"),
    path('charters-results/', views.chartersResults, name="chartersResults"),
    path('indictments-search/', views.indictmentsSearch, name="indictmentsSearch"),
    path('indictments-results/', views.indictmentsResults, name="indictmentsResults"),
    path('law-chancery-results/', views.lawChanceryResults, name="lawChanceryResults"),
    path('law-chancery-search/', views.lawChancerySearch, name="lawChancerySearch"),
    path('destruction-orders-search/', views.destructionOrdersSearch, name="destructionOrdersSearch"),
    path('destruction-orders-results/', views.destructionOrdersResults, name="destructionOrdersResults"),
    path('adoption-search/', views.adoptionSearch, name="adoptionSearch"),
    path('adoption-results/', views.adoptionResults, name="adoptionResults"),
    path('clerk-orders-search/', views.clerkOrdersSearch, name="clerkOrdersSearch"),
    path('clerk-orders-results/', views.clerkOrdersResults, name="clerkOrdersResults"),
    
    path('single-image/<str:section>/<str:pk>/', views.single_image_view, name="singleImage"),
    path('section-results/', views.view_section_results, name='sectionResults'),
   
]

    # path('single-image/bond/<str:pk>/', views.display_results_bond_books, name="singleImageBond"),
    # path('single-image/criminal/<str:pk>/', views.display_results_criminal, name="singleImageCriminal"),
    # path('single-image/civil/<str:pk>/', views.display_results_civil, name="singleImageCivil"),
    # path('single-image/criminal-cases/<str:pk>/', views.display_results_criminal_cases, name="singleImageCriminalCases"),
    # path('single-image/criminal-juvenile/<str:pk>/', views.display_results_ciminal_Juvenile, name="singleImageCriminalJuvenile"),
    # path('single-image/historic-index-cards/<str:pk>/', views.display_results_historic_index_cards, name="singleImageHistoricIndexCards"),
    # path('single-image/historic-order-books/<str:pk>/', views.display_results_historic_order_books, name="singleImageHistoricOrderBooks"),
    # path('single-image/hr/<str:pk>/', views.display_results_hr, name="singleImageHR"),
    # path('single-image/charters/<str:pk>/', views.display_results_charters, name="singleImageCharters"),
    # path('single-image/concealed-weapons/<str:pk>/', views.display_results_concealed_Weapons, name="singleImageConcealedWeapons"),
    # path('single-image/indictments/<str:pk>/', views.display_results_indictments, name="singleImageIndictments"),
    # path('single-image/law-chancery/<str:pk>/', views.display_results_law_chancery, name="singleImageLawChancery"),
    # path('single-image/destruction-orders/<str:pk>/', views.display_results_destruction_orders, name="singleImageDestructionOrders"),
    # path('single-image/adoption/<str:pk>/', views.display_results_adoption, name="singleImageAdoption"),
    # path('single-image/clerk-orders/<str:pk>/', views.display_results_clerk_orders, name="singleImageClerkOrders"),



     # path('single-image/<str:pk>/', views.display_results_bond_books, name="singleImage"),
    # path('single-image/<str:pk>/', views.display_results_criminal, name="singleImage"),
    # path('single-image/<str:pk>/', views.display_results_civil, name="singleImage"),
    # path('single-image/<str:pk>/', views.display_results_criminal_cases, name="singleImage"),
    # path('single-image/<str:pk>/', views.display_results_ciminal_Juvenile, name="singleImage"),
    # path('single-image/<str:pk>/', views.display_results_historic_index_cards, name="singleImage"),
    # path('single-image/<str:pk>/', views.display_results_historic_order_books, name="singleImage"),
    # path('single-image/<str:pk>/', views.display_results_hr, name="singleImage"),
    # path('single-image/<str:pk>/', views.display_results_charters, name="singleImage"),
    # path('single-image/<str:pk>/', views.display_results_concealed_Weapons, name="singleImage"),
    # path('single-image/<str:pk>/', views.display_results_indictments, name="singleImage"),
    # path('single-image/<str:pk>/', views.display_results_law_chancery, name="singleImage"),
    # path('single-image/<str:pk>/', views.display_results_destruction_orders, name="singleImage"),
    # path('single-image/<str:pk>/', views.display_results_adoption, name="singleImage"),
    # path('single-image/<str:pk>/', views.display_results_clerk_orders, name="singleImage"),
    # path('section-results/', views.view_section_results, name='sectionResults'),
    # path('section-results/', views.view_section_results, name='sectionResults'),